spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/ahblog?serverTimeZone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8

mybatis:
  type-aliases-package: com.hua.entity
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    root: info
    com.hua: debug
  file:
    path: log/blog-dev.log
server:
  port: 8081
